name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [ubuntu, macOS, windows]
        node: [18, 19]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run clean
      
  push:
    runs-on: build
    steps:
      - run: npm run build:release --if-present
      - run: |
          chmod +x ./dist/index.js
          git add dist
          git config --global user.name "Shin'ichi Ohno"
          git config --global user.email "ohno@cookpad.com"

          git diff --staged --quiet || git commit -am "Automated build"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
