name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run clean
      - run: npm run build:release --if-present
      - run: |
          chmod +x ./dist/index.js
          git add dist
          git config --global user.name "Shin'ichi Ohno"
          git config --global user.email "ohno@cookpad.com"
          git commit -am "Automated build"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
